
# Restart the application to have changes take effect. 
#
# Add sensitive or machine specific data to this file and it 
# will be available within the application under a CONFIG constant.
# Example: CONFIG[:secret_token]
#
# TODO: Create example file (this file is gitignored)

app_name: "Milemarker"

development:
  base_url: "milemarker.dev"
  mailer_username: "jtg03c"
  mailer_password: "Mazursux1!"
  secret_key_base: 8ad9e5e3f51ae7648497600adc7ec718d9afb736ac6f1b8e8bfc930ff9028fd8ee69b29c1b2c6d60bccccfb003eafb725a9d8e3747a97db12ad55894dee71eaa

test:
  base_url: "milemarker.dev"
  mailer_username: "jtg03c"
  mailer_password: "Mazursux1!"
  secret_key_base: 321ecc28ef05736034b8cb4a815c495aebf80420a22511cc3aeeeea74e0dafdc7a1c34f52ba7fcac7e703a47bfbb51c6096a274c1a6a7ba33b197a6729f88ae2 

production:
  base_url: "milemkr.com"
  mailer_username: ""
  mailer_password: ""
  secret_key_base: 15aa84ddf222b52bb17c7d91108a353d0c5fcb7c883b111a2a0102b062487805a325a0055095a998d0bcc4faceb492b4f8f61c1103e0b54fd201b9e57621e971 